# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.Product', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad')),
                ('product_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.ProductUOM', verbose_name='Producto y UM')),
                ('purchase_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.PurchaseList', verbose_name='Lista de compras')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseListItemResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad')),
                ('item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='django_purchase.PurchaseListItem')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='La cantidad en la unidad de medida de referencia', max_digits=8, verbose_name='Cantidad')),
                ('product_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.ProductUOM', verbose_name='Producto y UM')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.Vendor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default=datetime.date(9999, 12, 31), verbose_name='Fecha de fin')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.VendorProduct', verbose_name='Producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.ShippingMethod', verbose_name='Forma de envío')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.Vendor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorShippingMethodCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default=datetime.date(9999, 12, 31), verbose_name='Fecha de fin')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.VendorShippingMethod', verbose_name='Forma de envío')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaselistitemresolution',
            name='vendor_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.VendorProduct', verbose_name='Producto Proveedor'),
        ),
        migrations.AddField(
            model_name='productuom',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.UOM', verbose_name='UM'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorshippingmethod',
            unique_together=set([('vendor', 'shipping_method')]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorproduct',
            unique_together=set([('vendor', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='purchaselistitemresolution',
            unique_together=set([('item', 'vendor_product')]),
        ),
        migrations.AlterUniqueTogether(
            name='productuom',
            unique_together=set([('product', 'uom')]),
        ),
    ]
