# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuom',
            name='name',
            field=models.CharField(max_length=3, null=True, verbose_name='Nombre'),
        ),
    ]
