# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselistitemresolution',
            name='item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='django_purchase.PurchaseListItem'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaselistitemresolution',
            unique_together=set([('item', 'vendor_product')]),
        ),
    ]
