# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0004_auto_20170826_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
