# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0005_auto_20170826_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuom',
            old_name='UOM',
            new_name='uom',
        ),
    ]
