# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0006_auto_20170826_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.Partner', verbose_name='Partner')),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='vendorshippingmethod',
            name='partner',
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='django_purchase.Vendor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorshippingmethod',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='django_purchase.Vendor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
