# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0007_auto_20170826_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='partner',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('django_purchase.partner',),
        ),
    ]
