# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0008_auto_20170827_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseListItemResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad')),
                ('item', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, to='django_purchase.PurchaseListItem')),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_purchase.VendorProduct', verbose_name='Producto Proveedor')),
            ],
        ),
    ]
