# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_purchase', '0009_purchaselistitemresolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselistitemresolution',
            name='item',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='django_purchase.PurchaseListItem'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='name',
            field=models.CharField(max_length=3, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='productuom',
            unique_together=set([('product', 'uom')]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorproduct',
            unique_together=set([('vendor', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorshippingmethod',
            unique_together=set([('vendor', 'shipping_method')]),
        ),
    ]
